branches:
 only:
  - master

git:
 depth: 1

install:
 - mono .nuget/NuGet.exe restore Owin.Security.AesDataProtectorProvider.sln

language: csharp
solution: Owin.Security.AesDataProtectorProvider.sln

script:
 - xbuild /p:Platform="Any CPU" /p:Configuration=Release Owin.Security.AesDataProtectorProvider.sln /tv:12.0
